ItemEvents.modifyTooltips(event => {
  // event.add('item', '§6Description.')
    event.add('minecraft:red_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:blue_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:green_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:black_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:brown_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:cyan_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:gray_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:light_blue_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:light_gray_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:lime_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:magenta_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:orange_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:pink_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:purple_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:white_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:yellow_bed', '§6Sleeping on the same bed will make you feel more refreshed. You may also rest during the day on a hammock.')
    event.add('minecraft:saddle', '§6Horse somehow seems like a good travel option. Two players may ride the same horse.')
    event.add('minecraft:armor_stand', '§6Right click with an empty hand to swap armor.')
    event.add('crittersandcompanions:dragonfly_wing', '§6Feeding this to a Jumping Spider might make it docile.')
    event.add('minecraft:spider_eye', '§6Feeding this to a Dragonfly might make it docile.')
    event.add('create:brass_ingot', '§6Extreme heat is needed to forge this alloy.')
    event.add('crittersandcompanions:dumbo_octopus_bucket', '§6This cute cephalopod can save you from drowning.')
    event.add('supplementaries:cage', '§6May be used to transport small creatures.')
    event.add('create:empty_blaze_burner', '§6Made to trap an infernal creature within.')
    event.add('minecraft:brush', '§6Brush suspicious blocks to uncover their secrets. Find them in Temples, Ruins and many other structures.')
    event.add('betterarcheology:iron_brush', '§6Brush suspicious blocks to uncover their secrets. Find them in Temples, Ruins and many other structures.')
    event.add('betterarcheology:diamond_brush', '§6Brush suspicious blocks to uncover their secrets. Find them in Temples, Ruins and many other structures.')
    event.add('betterarcheology:netherite_brush', '§6Brush suspicious blocks to uncover their secrets. Find them in Temples, Ruins and many other structures.')
    event.add('minecraft:sniffer_egg', '§6Find this ancient egg in Warm Ocean underwater Ruins.')
    event.add('createaddition:straw', '§6A Blaze burner with a straw is able to intake fluids.')
    event.add('#minecraft:bundles', '§cEmpty your bundle before upgrading it.')
    event.add('kubejs:create_guide', '§6Interact to see ponders.')
    event.add('solcarrot:food_book', '§6Interact to check your food journey.')
    event.add('dungeonsdelight:wormouth', '§6It looks hungry.')


  })
