#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Apr 12 11:50:36 BRT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=BSL_v10.1.1.zip
