#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri May 15 11:09:23 BRT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=BSL_v10.1.1.zip
